module.exports = {
  BuyerInvoice: "object_45",
  Contract: "object_6",
  ContractInvoice: "object_35",
  SupplierInvoice: "object_44",
  TimeExpense: "object_33",
  lineItems: "object_37",
  contractAmendment: "object_47",
  proposalObject: "object_12",
  Worker: "object_30",
  Daily_scan: "object_62",
  Scan_notifications: "object_63",
  ExportLog: "object_66",
  teImportLog: "object_54",
  processLog: "object_68",
  requisitions: "object_10",
  contractsImportLogs: "object_70",
  Requester: "object_20",
  Buyer: "object_1",
  costCenters: "object_25",
  GLcodes: "object_58",
  BusinessUnit: "object_56",
  Suppliers: "object_2",
  mspSuperAdmin: "object_74",
  OpenPositionsData: "object_75",
};
